<%@ taglib uri="http://java.sun.com/portlet_2_0" prefix="portlet"%>

<portlet:defineObjects />

<span id="data_mini_nav_region"> 
<span id="triangle_sidebar_region">
<span id="dt_image_area">
    <img
	src="/portal-core/themes/pathport/images/mini_nav_triangle.png"
	alt="Disease Triangle diagram" usemap="#mininavdtmap" />
	<br/>
    <span id="mini_nav_triangle_links"> 
        <img id="explore_arrow" src="/portal-core/themes/pathport/images/small_right_arrow.png" /> 
        <span id="mini_nav_triangle_links_title">Continue Exploring</span>
        <br/>
    	<span class="triangle_link"><a href="Host">Host</a></span>
	    <span class="triangle_link"><a href="Pathogen">Pathogen</a></span>
	    <span class="triangle_link"><a href="Environment">Environment/Vector</a></span>
    </span>
</span>
</span>
</span>

<span id="data_main_region">
    <span class="page_main_title">Data</span>
	<span id="data_intro_blurb"> 
	Explore infectious disease pathosystems data sets.  Data sets were gathered from the BRCs, 
	NIAID-funded data generating projects, and other public resources/repositories.<br/>
	</span>
<br/>

<span id="data_category_region">

	<span class="page_subtitle">
	Host Response Data<br/>
	</span>    
    <span id="data_transcriptome_area">
             <span class="data_content_area">
		    <img src="/portal-core/pp/images/Transcription_label_en_small.jpg" alt="image representing transcriptome"/>
		      <span class="section_heading">
              <a href="/portal/portal/PathPort/ADB/ADB?action=a&windowstate=normal&c=hrds">View our Directory of Host Response Data Sets</a>
              </span>
            </span>
    </span>

	<span class="page_subtitle">
	Genome Data<br/>
	</span>    
		<span id="data_genome_area">
			    <span class="data_content_area"> 
			        <img src="/portal-core/pp/images/Quarter_of_Arthrobacter_arilaitensis_Re117_genome_small.png" alt="image representing genome"/>
			        <span class="data_ome_content">
				        <span class="section_heading">
				            <a href="/portal/portal/PathPort/Genome">Access our collection of Genome data.</a><br/>
                        </span>
					</span>
			    </span>
            
        </span>
</span>

<br/>
<br/>
<span class="page_subtitle">
	Legacy Data<br/>
</span>    

<span id="data_legacy_region" class="data_content_area">
    <span id="data_legacy_blurb_area">
    Explore data and reagents applicable to infectious disease research which were
    generated by previously funded NIAID resources.<br/>
    </span>
    <span id="pfgrc_region">
    Pathogen Functional Genomics Resource Center
    <br/>
        <span>
            <a href="/portal/portal/PathPort/ADB/ADB?action=a&windowstate=normal&c=pfgrcad" >PFGRC Array Designs</a>
        </span>
        <br/>
        <span>
            <a href="/portal/portal/PathPort/ADB/ADB?action=a&windowstate=normal&c=pfgrcmp" >PFGRC Microarray Protocols</a>
        </span>
        <br/>
        <span>
            <a href="/portal/portal/PathPort/ADB/ADB?action=a&windowstate=normal&c=pfgrcs" >PFGRC Software</a>
        </span>
        <br/>
    </span>
    
    <span id="prc_area">
    <span>
        <a href="/portal/portal/PathPort/ADB/ADB?action=a&windowstate=normal&c=prc" >Proteomics Resource Centers Data</a>
    </span>
    </span>
</span>